plugins {
    alias(libs.plugins.versions)
    alias(libs.plugins.version.catalog.update)
    alias(libs.plugins.spotless)
}


tasks.named("dependencyUpdates").configure {
    rejectVersionIf {
        it.candidate.version.contains("alpha") || it.candidate.version.contains("beta") || it.candidate.version.contains("rc")
    }
}

versionCatalogUpdate {
    keep {
        keepUnusedVersions = true
    }
}