# https://docs.gradle.org/current/userguide/platforms.html#sub::toml-dependencies-format
[versions]
assertj = "3.26.3"
junit-jupiter = "5.13.4"
log4j = "2.25.4"
mockito = "5.19.0"
pulsar = "4.2.1"
slf4j = "2.0.17"
testcontainers = "1.21.4"
guava = "33.4.8-jre"
pulsar-client-reactive = "0.7.0"
picocli = "4.7.7"
resilience4j = "2.3.0"
reactor-netty = "1.2.10"

[libraries]
assertj-core = { module = "org.assertj:assertj-core", version.ref = "assertj" }
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter", version.ref = "junit-jupiter" }
junit-jupiter-params = { module = "org.junit.jupiter:junit-jupiter-params", version.ref = "junit-jupiter" }
log4j-bom = { module = "org.apache.logging.log4j:log4j-bom", version.ref = "log4j" }
log4j-api = { module = "org.apache.logging.log4j:log4j-api", version.ref = "log4j" }
log4j-core = { module = "org.apache.logging.log4j:log4j-core", version.ref = "log4j" }
log4j-slf4j2-impl = { module = "org.apache.logging.log4j:log4j-slf4j2-impl", version.ref = "log4j" }
mockito-core = { module = "org.mockito:mockito-core", version.ref = "mockito" }
pulsar-client-all = { module = "org.apache.pulsar:pulsar-client-all", version.ref = "pulsar" }
pulsar-reactive-client = { module = "org.apache.pulsar:pulsar-client-reactive-adapter", version.ref = "pulsar-client-reactive" }
slf4j-api = { module = "org.slf4j:slf4j-api", version.ref = "slf4j" }
testcontainers-pulsar = { module = "org.testcontainers:pulsar", version.ref = "testcontainers" }
guava = { module = "com.google.guava:guava", version.ref = "guava" }
picocli = { module = "info.picocli:picocli" , version.ref = "picocli" }
resilience4j-retry = { module = "io.github.resilience4j:resilience4j-retry", version.ref = "resilience4j" }
reactor-netty = { module = "io.projectreactor.netty:reactor-netty", version.ref = "reactor-netty" }

[bundles]
log4j = [
    "log4j-api",
    "log4j-core",
    "log4j-slf4j2-impl",
    "slf4j-api",
]

[plugins]
version-catalog-update = "nl.littlerobots.version-catalog-update:1.0.0"
versions = "com.github.ben-manes.versions:0.52.0"
spotless = "com.diffplug.spotless:7.2.1"